#include <stdio.h>
#include <stdlib.h>

/* we will read the file has been generated by the previous code io4.c */


int main()
{
   int number;
   FILE *stream;  /* file pointer variable*/

   if ((stream = fopen("data.txt","r")) == NULL){
       printf("Error! in opening the file");

       /* It exits when the file pointer (stream) returns NULL. */ 
       exit(1);
   }

   fscanf(stream,"%d", &number);

   printf("The data file contains =%d", number);

   /*  we need to close the file after reading or writing*/

   fclose(stream); 
  
   return 0;
}